import 'package:flutter/material.dart';
import 'package:flutter/foundation.dart';
import 'package:shared_preferences/shared_preferences.dart';

const _kLocaleStorageKey = '__locale_key__';

class FFLocalizations {
  FFLocalizations(this.locale);

  final Locale locale;

  static FFLocalizations of(BuildContext context) =>
      Localizations.of<FFLocalizations>(context, FFLocalizations)!;

  static List<String> languages() => [
        'en',
        'es',
        'zh_Hans',
        'zh_Hant',
        'de',
        'nl',
        'ja',
        'hi',
        'af',
        'ar',
        'fr',
        'sv',
        'tr'
      ];

  static late SharedPreferences _prefs;
  static Future initialize() async =>
      _prefs = await SharedPreferences.getInstance();
  static Future storeLocale(String locale) =>
      _prefs.setString(_kLocaleStorageKey, locale);
  static Locale? getStoredLocale() {
    final locale = _prefs.getString(_kLocaleStorageKey);
    return locale != null && locale.isNotEmpty ? createLocale(locale) : null;
  }

  String get languageCode => locale.toString();
  String? get languageShortCode =>
      _languagesWithShortCode.contains(locale.toString())
          ? '${locale.toString()}_short'
          : null;
  int get languageIndex => languages().contains(languageCode)
      ? languages().indexOf(languageCode)
      : 0;

  String getText(String key) =>
      (kTranslationsMap[key] ?? {})[locale.toString()] ?? '';

  String getVariableText({
    String? enText = '',
    String? esText = '',
    String? zh_HansText = '',
    String? zh_HantText = '',
    String? deText = '',
    String? nlText = '',
    String? jaText = '',
    String? hiText = '',
    String? afText = '',
    String? arText = '',
    String? frText = '',
    String? svText = '',
    String? trText = '',
  }) =>
      [
        enText,
        esText,
        zh_HansText,
        zh_HantText,
        deText,
        nlText,
        jaText,
        hiText,
        afText,
        arText,
        frText,
        svText,
        trText
      ][languageIndex] ??
      '';

  static const Set<String> _languagesWithShortCode = {
    'ar',
    'az',
    'ca',
    'cs',
    'da',
    'de',
    'dv',
    'en',
    'es',
    'et',
    'fi',
    'fr',
    'gr',
    'he',
    'hi',
    'hu',
    'it',
    'km',
    'ku',
    'mn',
    'ms',
    'no',
    'pt',
    'ro',
    'ru',
    'rw',
    'sv',
    'th',
    'uk',
    'vi',
  };
}

class FFLocalizationsDelegate extends LocalizationsDelegate<FFLocalizations> {
  const FFLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) {
    final language = locale.toString();
    return FFLocalizations.languages().contains(
      language.endsWith('_')
          ? language.substring(0, language.length - 1)
          : language,
    );
  }

  @override
  Future<FFLocalizations> load(Locale locale) =>
      SynchronousFuture<FFLocalizations>(FFLocalizations(locale));

  @override
  bool shouldReload(FFLocalizationsDelegate old) => false;
}

Locale createLocale(String language) => language.contains('_')
    ? Locale.fromSubtags(
        languageCode: language.split('_').first,
        scriptCode: language.split('_').last,
      )
    : Locale(language);

final kTranslationsMap = <Map<String, Map<String, String>>>[
  // Health
  {
    's8r3i5uq': {
      'en': 'BALANCE.',
      'af': 'BALANS.',
      'ar': 'توازن.',
      'de': 'GLEICHGEWICHT.',
      'es': 'BALANCE.',
      'fr': 'ÉQUILIBRE.',
      'hi': 'संतुलन।',
      'ja': 'バランス。',
      'nl': 'EVENWICHT.',
      'sv': 'BALANS.',
      'tr': 'DENGE.',
      'zh_Hans': '平衡。',
      'zh_Hant': '平衡。',
    },
    'r26xbcvp': {
      'en': 'Health',
      'af': 'Gesondheid',
      'ar': 'صحة',
      'de': 'Gesundheit',
      'es': 'Salud',
      'fr': 'Santé',
      'hi': 'स्वास्थ्य',
      'ja': '健康',
      'nl': 'Gezondheid',
      'sv': 'Hälsa',
      'tr': 'Sağlık',
      'zh_Hans': '健康',
      'zh_Hant': '健康',
    },
  },
  // Settings
  {
    '5ixzwgjl': {
      'en': 'Settings',
      'af': 'Instellings',
      'ar': 'إعدادات',
      'de': 'Einstellungen',
      'es': 'Ajustes',
      'fr': 'Paramètres',
      'hi': 'समायोजन',
      'ja': '設定',
      'nl': 'Instellingen',
      'sv': 'inställningar',
      'tr': 'Ayarlar',
      'zh_Hans': '设置',
      'zh_Hant': '設置',
    },
    'swzt9q4e': {
      'en': 'Settings',
      'af': 'Instellings',
      'ar': 'إعدادات',
      'de': 'Einstellungen',
      'es': 'Ajustes',
      'fr': 'Paramètres',
      'hi': 'समायोजन',
      'ja': '設定',
      'nl': 'Instellingen',
      'sv': 'inställningar',
      'tr': 'Ayarlar',
      'zh_Hans': '设置',
      'zh_Hant': '設置',
    },
    'u7hxk5d1': {
      'en': 'Profile',
      'af': 'Profiel',
      'ar': 'حساب تعريفي',
      'de': 'Profil',
      'es': 'Perfil',
      'fr': 'Profil',
      'hi': 'प्रोफ़ाइल',
      'ja': 'プロフィール',
      'nl': 'Profiel',
      'sv': 'Profil',
      'tr': 'Profil',
      'zh_Hans': '轮廓',
      'zh_Hant': '輪廓',
    },
    '5o0l7654': {
      'en': 'Theme',
      'af': 'Tema',
      'ar': 'سمة',
      'de': 'Thema',
      'es': 'Tema',
      'fr': 'Thème',
      'hi': 'विषय',
      'ja': 'テーマ',
      'nl': 'Thema',
      'sv': 'Tema',
      'tr': 'Tema',
      'zh_Hans': '主题',
      'zh_Hant': '主題',
    },
    'whjue41r': {
      'en': 'Notifications',
      'af': 'Kennisgewinginstellings',
      'ar': 'إعدادات الإشعار',
      'de': 'Benachrichtigungseinstellungen',
      'es': 'Configuración de las notificaciones',
      'fr': 'Paramètres de notification',
      'hi': 'अधिसूचना सेटिंग्स',
      'ja': '通知設定',
      'nl': 'Notificatie instellingen',
      'sv': 'Aviseringsinställningar',
      'tr': 'Bildirim ayarları',
      'zh_Hans': '通知设置',
      'zh_Hant': '通知設置',
    },
    'gdjpjpgx': {
      'en': 'Support',
      'af': 'Ondersteuning',
      'ar': 'يدعم',
      'de': 'Unterstützung',
      'es': 'Apoyo',
      'fr': 'Soutien',
      'hi': 'सहायता',
      'ja': 'サポート',
      'nl': 'Steun',
      'sv': 'Stöd',
      'tr': 'Destek',
      'zh_Hans': '支持',
      'zh_Hant': '支持',
    },
    't9jxktoz': {
      'en': 'Settings',
      'af': 'Instellings',
      'ar': 'إعدادات',
      'de': 'Einstellungen',
      'es': 'Ajustes',
      'fr': 'Paramètres',
      'hi': 'समायोजन',
      'ja': '設定',
      'nl': 'Instellingen',
      'sv': 'inställningar',
      'tr': 'Ayarlar',
      'zh_Hans': '设置',
      'zh_Hant': '設置',
    },
  },
  // SignUp
  {
    'wwtrpl53': {
      'en': 'BALANCE.',
      'af': 'BALANS.',
      'ar': 'توازن.',
      'de': 'GLEICHGEWICHT.',
      'es': 'BALANCE.',
      'fr': 'ÉQUILIBRE.',
      'hi': 'संतुलन।',
      'ja': 'バランス。',
      'nl': 'EVENWICHT.',
      'sv': 'BALANS.',
      'tr': 'DENGE.',
      'zh_Hans': '平衡。',
      'zh_Hant': '平衡。',
    },
    'qbq8srbu': {
      'en': 'Create an account',
      'af': 'Maak \'n rekening oop',
      'ar': 'إنشاء حساب',
      'de': 'Ein Konto erstellen',
      'es': 'Crea una cuenta',
      'fr': 'Créer un compte',
      'hi': 'खाता बनाएं',
      'ja': 'アカウントを作成する',
      'nl': 'Account aanmaken',
      'sv': 'Skapa ett konto',
      'tr': 'Bir hesap oluşturun',
      'zh_Hans': '创建一个帐户',
      'zh_Hant': '創建一個帳戶',
    },
    '1oc7093e': {
      'en': 'Let\'s get started by filling out the information below.',
      'af': 'Kom ons begin deur die inligting hieronder in te vul.',
      'ar': 'لنبدأ بملء المعلومات أدناه.',
      'de': 'Beginnen wir mit dem Ausfüllen der folgenden Informationen.',
      'es': 'Comencemos completando la información a continuación.',
      'fr': 'Commençons par remplir les informations ci-dessous.',
      'hi': 'आइए नीचे दी गई जानकारी भरकर शुरुआत करें।',
      'ja': '以下の情報を入力して始めましょう。',
      'nl':
          'Laten we aan de slag gaan door de onderstaande informatie in te vullen.',
      'sv': 'Låt oss komma igång genom att fylla i informationen nedan.',
      'tr': 'Aşağıdaki bilgileri doldurarak başlayalım.',
      'zh_Hans': '让我们开始填写以下信息。',
      'zh_Hant': '讓我們開始填寫以下信息。',
    },
    'cvk591dg': {
      'en': 'Email',
      'af': 'E-pos',
      'ar': 'بريد إلكتروني',
      'de': 'Email',
      'es': 'Correo electrónico',
      'fr': 'E-mail',
      'hi': 'ईमेल',
      'ja': 'Eメール',
      'nl': 'E-mail',
      'sv': 'E-post',
      'tr': 'E-posta',
      'zh_Hans': '电子邮件',
      'zh_Hant': '電子郵件',
    },
    'ygve12uv': {
      'en': 'Password',
      'af': 'Wagwoord',
      'ar': 'كلمة المرور',
      'de': 'Passwort',
      'es': 'Contraseña',
      'fr': 'Mot de passe',
      'hi': 'पासवर्ड',
      'ja': 'パスワード',
      'nl': 'Wachtwoord',
      'sv': 'Lösenord',
      'tr': 'Şifre',
      'zh_Hans': '密码',
      'zh_Hant': '密碼',
    },
    '202aehow': {
      'en': 'Confirm Password',
      'af': 'Bevestig Wagwoord',
      'ar': 'تأكيد كلمة المرور',
      'de': 'Bestätige das Passwort',
      'es': 'confirmar Contraseña',
      'fr': 'Confirmez le mot de passe',
      'hi': 'पासवर्ड की पुष्टि कीजिये',
      'ja': 'パスワードを認証する',
      'nl': 'bevestig wachtwoord',
      'sv': 'Bekräfta lösenord',
      'tr': 'Şifreyi Onayla',
      'zh_Hans': '确认密码',
      'zh_Hant': '確認密碼',
    },
    'timq8fo3': {
      'en': 'Create Account',
      'af': 'Skep rekening',
      'ar': 'إنشاء حساب',
      'de': 'Benutzerkonto erstellen',
      'es': 'Crear una cuenta',
      'fr': 'Créer un compte',
      'hi': 'खाता बनाएं',
      'ja': 'アカウントを作成する',
      'nl': 'Account aanmaken',
      'sv': 'Skapa konto',
      'tr': 'Hesap oluşturmak',
      'zh_Hans': '创建账户',
      'zh_Hant': '創建賬戶',
    },
    'x6z5g8v3': {
      'en': 'OR',
      'af': 'OF',
      'ar': 'أو',
      'de': 'ODER',
      'es': 'O',
      'fr': 'OU',
      'hi': 'या',
      'ja': 'または',
      'nl': 'OF',
      'sv': 'ELLER',
      'tr': 'VEYA',
      'zh_Hans': '或者',
      'zh_Hant': '或者',
    },
    'v1t3d2ef': {
      'en': 'Continue with Google',
      'af': 'Gaan voort met Google',
      'ar': 'تواصل مع جوجل',
      'de': 'Weiter mit Google',
      'es': 'Continuar con Google',
      'fr': 'Continuer avec Google',
      'hi': 'Google के साथ जारी रखें',
      'ja': 'Google を続ける',
      'nl': 'Ga verder met Google',
      'sv': 'Fortsätt med Google',
      'tr': 'Google ile devam',
      'zh_Hans': '继续使用谷歌',
      'zh_Hant': '繼續使用谷歌',
    },
    'bb8ouwuh': {
      'en': 'Continue with Apple',
      'af': 'Gaan voort met Apple',
      'ar': 'تواصل مع أبل',
      'de': 'Weiter mit Apple',
      'es': 'Continuar con Apple',
      'fr': 'Continuer avec Apple',
      'hi': 'एप्पल के साथ जारी रखें',
      'ja': 'アップルを使い続ける',
      'nl': 'Ga verder met Apple',
      'sv': 'Fortsätt med Apple',
      'tr': 'Apple ile devam et',
      'zh_Hans': '继续使用苹果',
      'zh_Hant': '繼續使用蘋果',
    },
    'erwy85cy': {
      'en': 'Already have an account? ',
      'af': 'Reeds \'n rekening?',
      'ar': 'هل لديك حساب؟',
      'de': 'Sie haben bereits ein Konto?',
      'es': '¿Ya tienes una cuenta?',
      'fr': 'Vous avez déjà un compte?',
      'hi': 'क्या आपके पास पहले से एक खाता मौजूद है?',
      'ja': 'すでにアカウントをお持ちですか？',
      'nl': 'Heb je al een account?',
      'sv': 'Har du redan ett konto?',
      'tr': 'Zaten hesabınız var mı?',
      'zh_Hans': '已经有帐户？',
      'zh_Hant': '已經有帳戶？',
    },
    'i412xonl': {
      'en': ' Sign In here',
      'af': 'Meld hier aan',
      'ar': 'تسجيل الدخول هنا',
      'de': 'Hier anmelden',
      'es': 'Firme aquí',
      'fr': 'Se connecter ici',
      'hi': 'यहां साइन इन करो',
      'ja': 'ここにサインインしてください',
      'nl': 'Meld je hier aan',
      'sv': 'Logga in här',
      'tr': 'Oturum açın',
      'zh_Hans': '在此登录',
      'zh_Hant': '在此登錄',
    },
    'ga9nissl': {
      'en': 'Home',
      'af': 'Tuis',
      'ar': 'بيت',
      'de': 'Heim',
      'es': 'Hogar',
      'fr': 'Maison',
      'hi': 'घर',
      'ja': '家',
      'nl': 'Thuis',
      'sv': 'Hem',
      'tr': 'Ev',
      'zh_Hans': '家',
      'zh_Hant': '家',
    },
  },
  // Workout
  {
    'ghjgh5w0': {
      'en': 'Let\'s Workout',
      'af': 'Aanbevole oefensessies',
      'ar': 'التدريبات الموصى بها',
      'de': 'Empfohlene Trainingseinheiten',
      'es': 'Entrenamientos recomendados',
      'fr': 'Entraînements recommandés',
      'hi': 'अनुशंसित वर्कआउट',
      'ja': '推奨されるトレーニング',
      'nl': 'Aanbevolen trainingen',
      'sv': 'Rekommenderade träningspass',
      'tr': 'Önerilen Antrenmanlar',
      'zh_Hans': '推荐锻炼',
      'zh_Hant': '推薦鍛煉',
    },
    'ejlhi3u1': {
      'en': 'Start New Workout',
      'af': 'Begin nuwe oefensessie',
      'ar': 'ابدأ تمرينًا جديدًا',
      'de': 'Starten Sie ein neues Training',
      'es': 'Iniciar nuevo entrenamiento',
      'fr': 'Commencer un nouvel entraînement',
      'hi': 'नया वर्कआउट शुरू करें',
      'ja': '新しいワークアウトを開始する',
      'nl': 'Nieuwe training starten',
      'sv': 'Starta nytt träningspass',
      'tr': 'Yeni Antrenmana Başla',
      'zh_Hans': '开始新的锻炼',
      'zh_Hant': '開始新的鍛煉',
    },
    'imsaf5u9': {
      'en': 'My Routines',
      'af': 'My Roetines',
      'ar': 'روتيني',
      'de': 'Meine Routinen',
      'es': 'mis rutinas',
      'fr': 'Mes Routines',
      'hi': 'मेरी दिनचर्या',
      'ja': '私のルーティン',
      'nl': 'Mijn routines',
      'sv': 'Mina rutiner',
      'tr': 'Rutinlerim',
      'zh_Hans': '我的日常',
      'zh_Hant': '我的日常',
    },
    'pofpqoyy': {
      'en': 'Last Performed 2 days ago',
      'af': 'Laas uitgevoer 2 dae gelede',
      'ar': 'تم آخر تنفيذ منذ يومين',
      'de': 'Zuletzt vor 2 Tagen aufgeführt',
      'es': 'Realizado por última vez hace 2 días',
      'fr': 'Dernière exécution il y a 2 jours',
      'hi': 'अंतिम प्रदर्शन 2 दिन पहले किया गया',
      'ja': '最後に実行されたのは 2 日前',
      'nl': 'Laatst uitgevoerd 2 dagen geleden',
      'sv': 'Uppfördes senast för 2 dagar sedan',
      'tr': 'En Son 2 gün önce Gerçekleştirildi',
      'zh_Hans': '上次表演 2 天前',
      'zh_Hant': '上次表演 2 天前',
    },
    'z1wdqigq': {
      'en': 'Pull',
      'af': 'Trek',
      'ar': 'يحذب',
      'de': 'Ziehen',
      'es': 'Jalar',
      'fr': 'Tirer',
      'hi': 'खींचो',
      'ja': '引く',
      'nl': 'Trekken',
      'sv': 'Dra',
      'tr': 'Çekmek',
      'zh_Hans': '拉',
      'zh_Hant': '拉',
    },
    'i9k5ep8o': {
      'en': 'Last Performed 4 days ago',
      'af': 'Laas uitgevoer 4 dae gelede',
      'ar': 'تم آخر تنفيذ منذ 4 أيام',
      'de': 'Zuletzt vor 4 Tagen aufgeführt',
      'es': 'Realizado por última vez hace 4 días',
      'fr': 'Dernière exécution il y a 4 jours',
      'hi': 'अंतिम प्रदर्शन 4 दिन पहले किया गया',
      'ja': '最後に実行されたのは 4 日前',
      'nl': '4 dagen geleden voor het laatst uitgevoerd',
      'sv': 'Uppfördes senast för 4 dagar sedan',
      'tr': 'En Son 4 gün önce Gerçekleştirildi',
      'zh_Hans': '上次表演 4 天前',
      'zh_Hant': '上次表演 4 天前',
    },
    'cyj9xgzi': {
      'en':
          '6x Lat Pulldowns (Cable)\n4x Seated Rows (Cable)\n3x Bicep Curls (Barbell)\n3x T-Bar Rows \n3x Hammer Curls (Dumbbell)\n3x Shrugs (Dumbbell)',
      'af':
          '6x Lat Pulldowns (kabel)\n4x sittende rye (kabel)\n3x Bicep Curls (Bicep Curls)\n3x T-staaf rye\n3x Hammer Curls (Dumbbell)\n3x Shrugs (Dumbbell)',
      'ar':
          '6x Lat Pulldowns (كابل)\n4x صفوف جلوس (كابل)\n3 تمرينات للعضلة ذات الرأسين (باربيل)\n3x T-Bar Rows\n3x Hammer Curls (دمبل)\n3x هزات (الدمبل)',
      'de':
          '6x Latzug (Kabelzug)\n4x Sitzrudern (Kabel)\n3x Bizepscurls (Langhantel)\n3x T-Bar-Reihen\n3x Hammercurls (Hantel)\n3x Achselzucken (Hantel)',
      'es':
          '6x Lat Pulldowns (cable)\n4x filas sentadas (cable)\n3x curl de bíceps (barra)\n3 filas con barra en T\n3x Hammer Curls (con mancuernas)\n3x encogimientos de hombros (mancuerna)',
      'fr':
          '6x Lat Pulldowns (câble)\n4x rangées assises (câble)\n3x boucles de biceps (haltère)\n3x rangées de barres en T\n3x boucles marteau (haltère)\n3x haussements d\'épaules (haltères)',
      'hi':
          '6x लैट पुलडाउन (केबल)\n4x बैठी हुई पंक्तियाँ (केबल)\n3x बाइसेप कर्ल्स (बारबेल)\n3x टी-बार पंक्तियाँ\n3x हैमर कर्ल (डम्बल)\n3x श्रग्स (डम्बल)',
      'ja':
          '6x ラットプルダウン (ケーブル)\n4x 着席列 (ケーブル)\n3x 上腕二頭筋カール (バーベル)\n3x Tバー列\n3x ハンマーカール (ダンベル)\n3x シュラッグ (ダンベル)',
      'nl':
          '6x Lat Pulldowns (kabel)\n4x zittende rijen (kabel)\n3x Bicep Curls (Barbell)\n3x T-bar rijen\n3x Hammer Curls (halter)\n3x haalt zijn schouders op (halter)',
      'sv':
          '6x Lat Pulldowns (kabel)\n4x sittande rader (kabel)\n3x Bicep Curls (skivstång)\n3x T-Bar rader\n3x Hammer Curls (Hantel)\n3x axelryckningar (hantel)',
      'tr':
          '6x Lat Pulldowns (Kablo)\n4x Oturan Sıralar (Kablo)\n3x Pazı Bukleler (Halter)\n3x T-Bar Satırları\n3x Hammer Curls (Dambıl)\n3x Omuz silkme (Halter)',
      'zh_Hans':
          '6 次高位下拉（绳索）\n4x 坐式划船（缆绳）\n3x 二头肌弯举（杠铃）\n3x T 形划船\n3x 锤式弯举（哑铃）\n3x 耸肩（哑铃）',
      'zh_Hant':
          '6 次高位下拉（繩索）\n4x 坐式划船（纜繩）\n3x 二頭肌彎舉（槓鈴）\n3x T 形划船\n3x 錘式彎舉（啞鈴）\n3x 聳肩（啞鈴）',
    },
    'ov1fjobt': {
      'en': 'Legs',
      'af': 'Bene',
      'ar': 'أرجل',
      'de': 'Beine',
      'es': 'Piernas',
      'fr': 'Jambes',
      'hi': 'पैर',
      'ja': '脚',
      'nl': 'Benen',
      'sv': 'Ben',
      'tr': 'bacaklar',
      'zh_Hans': '腿',
      'zh_Hant': '腿',
    },
    '3ejytq91': {
      'en': 'Last Performed 5 days ago',
      'af': 'Laas uitgevoer 5 dae gelede',
      'ar': 'تم آخر تنفيذ منذ 5 أيام',
      'de': 'Zuletzt vor 5 Tagen aufgeführt',
      'es': 'Última realización hace 5 días',
      'fr': 'Dernière exécution il y a 5 jours',
      'hi': 'अंतिम प्रदर्शन 5 दिन पहले किया गया',
      'ja': '最後に実行されたのは 5 日前',
      'nl': '5 dagen geleden voor het laatst uitgevoerd',
      'sv': 'Senast framförd för 5 dagar sedan',
      'tr': 'En Son 5 gün önce Gerçekleştirildi',
      'zh_Hans': '最后执行时间 5 天前',
      'zh_Hant': '最後執行時間 5 天前',
    },
    'f79y2fm5': {
      'en':
          '5x Deadlift (Barbell)\n4x Squats (Barbell)\n3x Seated Leg Curl (Machine)\n3x Leg Extension (Machine)\n3x Calf raises (Machine)',
      'af':
          '5x Deadlift (Barbell)\n4x Squats (Barbell)\n3x sittende beenkrul (masjien)\n3x beenverlenging (masjien)\n3x Kuitverhogings (masjien)',
      'ar':
          '5x Deadlift (Barbell)\n4x قرفصاء (باربل)\nتمرين ثني الأرجل بثلاث مرات (الجهاز)\n3x تمديد الساق (آلة)\n3 مرات يرفع ربلة الساق (آلة)',
      'de':
          '5x Kreuzheben (Langhantel)\n4x Kniebeugen (Langhantel)\n3x Beinbeuger im Sitzen (Maschine)\n3x Beinstrecker (Maschine)\n3x Wadenheben (Maschine)',
      'es':
          '5x peso muerto (barra)\n4x sentadillas (barra)\n3x Curl de piernas sentado (Máquina)\nExtensión de pierna 3x (Máquina)\n3x Elevaciones de pantorrillas (Máquina)',
      'fr':
          '5x soulevé de terre (haltère)\n4x Squats (Barres)\n3x Flexion des jambes assise (machine)\n3x extension de jambe (machine)\n3x Mollets (Machine)',
      'hi':
          '5x डेडलिफ्ट (बारबेल)\n4x स्क्वैट्स (बारबेल)\n3x सीटेड लेग कर्ल (मशीन)\n3x लेग एक्सटेंशन (मशीन)\n3 बार बछड़ा पालना (मशीन)',
      'ja':
          '5x デッドリフト (バーベル)\nスクワット 4 回 (バーベル)\n3x シーテッドレッグカール (マシン)\n3x レッグエクステンション (マシン)\nカーフレイズ3回（マシン）',
      'nl':
          '5x Deadlift (lange halter)\n4x Squats (lange halter)\n3x Zittende Leg Curl (Machine)\n3x beenverlenging (machine)\n3x kuitverhogingen (machine)',
      'sv':
          '5x marklyft (skivstång)\n4x knäböj (skivstång)\n3x sittande bencurl (maskin)\n3x benförlängning (maskin)\n3x vadhöjningar (maskin)',
      'tr':
          '5x Deadlift (Halter)\n4x Squat (Halter)\n3x Oturmuş Bacak Kıvırma (Makine)\n3x Bacak Uzatma (Makine)\n3x Buzağı yükseltmesi (Makine)',
      'zh_Hans': '5 次硬拉（杠铃）\n4x 深蹲（杠铃）\n3x 坐式腿弯举（机器）\n3x 腿部伸展（机器）\n3 次小腿抬高（机器）',
      'zh_Hant': '5 次硬拉（槓鈴）\n4x 深蹲（槓鈴）\n3x 坐式腿彎舉（機器）\n3x 腿部伸展（機器）\n3 次小腿抬高（機器）',
    },
    'bc7cf98z': {
      'en': 'BALANCE.',
      'af': 'BALANS.',
      'ar': 'توازن.',
      'de': 'GLEICHGEWICHT.',
      'es': 'BALANCE.',
      'fr': 'ÉQUILIBRE.',
      'hi': 'संतुलन।',
      'ja': 'バランス。',
      'nl': 'EVENWICHT.',
      'sv': 'BALANS.',
      'tr': 'DENGE.',
      'zh_Hans': '平衡。',
      'zh_Hant': '平衡。',
    },
    'yxtektu5': {
      'en': 'Workout',
      'af': 'Oefensessie',
      'ar': 'اكتشف - حل',
      'de': 'Trainieren',
      'es': 'Ejercicio',
      'fr': 'Entraînement',
      'hi': 'कसरत करना',
      'ja': 'いい結果',
      'nl': 'Training',
      'sv': 'Träna',
      'tr': 'Antrenman yapmak',
      'zh_Hans': '锻炼',
      'zh_Hant': '鍛煉',
    },
  },
  // Home
  {
    'n80x0pjn': {
      'en': 'BALANCE.',
      'af': 'BALANS.',
      'ar': 'توازن.',
      'de': 'GLEICHGEWICHT.',
      'es': 'BALANCE.',
      'fr': 'ÉQUILIBRE.',
      'hi': 'संतुलन।',
      'ja': 'バランス。',
      'nl': 'EVENWICHT.',
      'sv': 'BALANS.',
      'tr': 'DENGE.',
      'zh_Hans': '平衡。',
      'zh_Hant': '平衡。',
    },
    'xuw9dcd1': {
      'en': 'Welcome.',
      'af': 'Aanbevole oefensessies',
      'ar': 'التدريبات الموصى بها',
      'de': 'Empfohlene Trainingseinheiten',
      'es': 'Entrenamientos recomendados',
      'fr': 'Entraînements recommandés',
      'hi': 'अनुशंसित वर्कआउट',
      'ja': '推奨されるトレーニング',
      'nl': 'Aanbevolen trainingen',
      'sv': 'Rekommenderade träningspass',
      'tr': 'Önerilen Antrenmanlar',
      'zh_Hans': '推荐锻炼',
      'zh_Hant': '推薦鍛煉',
    },
    '2tzrzp82': {
      'en': 'Workout History',
      'af': 'Oefensessie geskiedenis',
      'ar': 'تاريخ التمرين',
      'de': 'Trainingsverlauf',
      'es': 'Historial de entrenamiento',
      'fr': 'Historique d\'entraînement',
      'hi': 'कसरत का इतिहास',
      'ja': 'トレーニング履歴',
      'nl': 'Trainingsgeschiedenis',
      'sv': 'Träningshistorik',
      'tr': 'Antrenman Geçmişi',
      'zh_Hans': '锻炼历史',
      'zh_Hant': '鍛煉歷史',
    },
    'tviu6xrv': {
      'en': 'Workouts This Week',
      'af': 'Gewig',
      'ar': 'وزن',
      'de': 'Gewicht',
      'es': 'Peso',
      'fr': 'Poids',
      'hi': 'वज़न',
      'ja': '重さ',
      'nl': 'Gewicht',
      'sv': 'Vikt',
      'tr': 'Ağırlık',
      'zh_Hans': '重量',
      'zh_Hant': '重量',
    },
    '05ip066l': {
      'en': 'Home',
      'af': 'Tuis',
      'ar': 'بيت',
      'de': 'Heim',
      'es': 'Hogar',
      'fr': 'Maison',
      'hi': 'घर',
      'ja': '家',
      'nl': 'Thuis',
      'sv': 'Hem',
      'tr': 'Ev',
      'zh_Hans': '家',
      'zh_Hant': '家',
    },
  },
  // Profile
  {
    'bayrzuvo': {
      'en': 'Profile',
      'af': 'Profiel',
      'ar': 'حساب تعريفي',
      'de': 'Profil',
      'es': 'Perfil',
      'fr': 'Profil',
      'hi': 'प्रोफ़ाइल',
      'ja': 'プロフィール',
      'nl': 'Profiel',
      'sv': 'Profil',
      'tr': 'Profil',
      'zh_Hans': '轮廓',
      'zh_Hant': '輪廓',
    },
    'pmarjxhg': {
      'en': 'Change Picture',
      'af': 'Verander prentjie',
      'ar': 'تغيير الصورة',
      'de': 'Bild ändern',
      'es': 'Cambiar imagen',
      'fr': 'Changer l\'image',
      'hi': 'चित्र बदलें',
      'ja': '写真を変える',
      'nl': 'Verander afbeelding',
      'sv': 'Byt bild',
      'tr': 'Resmi değiştir',
      'zh_Hans': '更换图片',
      'zh_Hant': '更換圖片',
    },
    'yk9n7qac': {
      'en': 'Change Name',
      'af': 'Verander naam',
      'ar': 'تغيير الإسم',
      'de': 'Namen ändern',
      'es': 'Cambiar nombre',
      'fr': 'Changer de nom',
      'hi': 'नाम परिवर्तन करें',
      'ja': '名前の変更',
      'nl': 'Naam veranderen',
      'sv': 'Byt namn',
      'tr': 'İsmini değiştir',
      'zh_Hans': '更换名字',
      'zh_Hant': '更換名字',
    },
    'anb5kbi0': {
      'en': 'Characters must be from 3-12',
      'af': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'nl': '',
      'sv': '',
      'tr': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'b8syjk7e': {
      'en': 'Your username is too short',
      'af': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'nl': '',
      'sv': '',
      'tr': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '69mjcu0r': {
      'en': 'Your username is too long',
      'af': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'nl': '',
      'sv': '',
      'tr': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '6kbxkxjb': {
      'en': 'Please choose an option from the dropdown',
      'af': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'nl': '',
      'sv': '',
      'tr': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'y9rtj8s1': {
      'en': 'Logout',
      'af': 'Teken uit',
      'ar': 'تسجيل خروج',
      'de': 'Ausloggen',
      'es': 'Cerrar sesión',
      'fr': 'Se déconnecter',
      'hi': 'लॉग आउट',
      'ja': 'ログアウト',
      'nl': 'Uitloggen',
      'sv': 'Logga ut',
      'tr': 'Çıkış Yap',
      'zh_Hans': '登出',
      'zh_Hant': '登出',
    },
    '4ivamu95': {
      'en': 'Profile',
      'af': 'Profiel',
      'ar': 'حساب تعريفي',
      'de': 'Profil',
      'es': 'Perfil',
      'fr': 'Profil',
      'hi': 'प्रोफ़ाइल',
      'ja': 'プロフィール',
      'nl': 'Profiel',
      'sv': 'Profil',
      'tr': 'Profil',
      'zh_Hans': '轮廓',
      'zh_Hant': '輪廓',
    },
  },
  // SignIn
  {
    'bki6fcpc': {
      'en': 'BALANCE.',
      'af': 'BALANS.',
      'ar': 'توازن.',
      'de': 'GLEICHGEWICHT.',
      'es': 'BALANCE.',
      'fr': 'ÉQUILIBRE.',
      'hi': 'संतुलन।',
      'ja': 'バランス。',
      'nl': 'EVENWICHT.',
      'sv': 'BALANS.',
      'tr': 'DENGE.',
      'zh_Hans': '平衡。',
      'zh_Hant': '平衡。',
    },
    '11uarqkt': {
      'en': 'Welcome Back',
      'af': 'Welkom terug',
      'ar': 'مرحبًا بعودتك',
      'de': 'Willkommen zurück',
      'es': 'Bienvenido de nuevo',
      'fr': 'Content de te revoir',
      'hi': 'वापसी पर स्वागत है',
      'ja': 'おかえり',
      'nl': 'Welkom terug',
      'sv': 'Välkommen tillbaka',
      'tr': 'Tekrar hoşgeldiniz',
      'zh_Hans': '欢迎回来',
      'zh_Hant': '歡迎回來',
    },
    'gauwov03': {
      'en': 'Let\'s get back into it by filling the information below.',
      'af': 'Kom ons gaan terug daarop deur die inligting hieronder in te vul.',
      'ar': 'دعنا نعود إليها بملء المعلومات أدناه.',
      'de':
          'Lassen Sie uns darauf zurückkommen, indem Sie die folgenden Informationen ausfüllen.',
      'es': 'Volvamos a eso completando la información a continuación.',
      'fr': 'Revenons-y en remplissant les informations ci-dessous.',
      'hi': 'आइए नीचे दी गई जानकारी भरकर इसमें वापस आएं।',
      'ja': '以下の情報を入力して本題に戻りましょう。',
      'nl':
          'Laten we er weer op ingaan door de onderstaande informatie in te vullen.',
      'sv':
          'Låt oss komma tillbaka till det genom att fylla i informationen nedan.',
      'tr': 'Aşağıdaki bilgileri doldurarak geri dönelim.',
      'zh_Hans': '让我们通过填写以下信息来回到它。',
      'zh_Hant': '讓我們通過填寫以下信息來回到它。',
    },
    '221upj73': {
      'en': 'Email',
      'af': 'E-pos',
      'ar': 'بريد إلكتروني',
      'de': 'Email',
      'es': 'Correo electrónico',
      'fr': 'E-mail',
      'hi': 'ईमेल',
      'ja': 'Eメール',
      'nl': 'E-mail',
      'sv': 'E-post',
      'tr': 'E-posta',
      'zh_Hans': '电子邮件',
      'zh_Hant': '電子郵件',
    },
    'h4vuaqgq': {
      'en': 'Password',
      'af': 'Wagwoord',
      'ar': 'كلمة المرور',
      'de': 'Passwort',
      'es': 'Contraseña',
      'fr': 'Mot de passe',
      'hi': 'पासवर्ड',
      'ja': 'パスワード',
      'nl': 'Wachtwoord',
      'sv': 'Lösenord',
      'tr': 'Şifre',
      'zh_Hans': '密码',
      'zh_Hant': '密碼',
    },
    'y0ybyt83': {
      'en': 'Sign In',
      'af': 'Meld aan',
      'ar': 'تسجيل الدخول',
      'de': 'Anmelden',
      'es': 'Iniciar sesión',
      'fr': 'Se connecter',
      'hi': 'दाखिल करना',
      'ja': 'サインイン',
      'nl': 'Aanmelden',
      'sv': 'Logga in',
      'tr': 'Kayıt olmak',
      'zh_Hans': '登入',
      'zh_Hant': '登入',
    },
    'x1cw61qr': {
      'en': 'OR',
      'af': 'OF',
      'ar': 'أو',
      'de': 'ODER',
      'es': 'O',
      'fr': 'OU',
      'hi': 'या',
      'ja': 'または',
      'nl': 'OF',
      'sv': 'ELLER',
      'tr': 'VEYA',
      'zh_Hans': '或者',
      'zh_Hant': '或者',
    },
    'jrdt1yo5': {
      'en': 'Sign in with Google',
      'af': 'Meld aan met Google',
      'ar': 'الدخول مع جوجل',
      'de': 'Anmeldung mit Google',
      'es': 'Inicia sesión con Google',
      'fr': 'Connectez-vous avec Google',
      'hi': 'Google से साइन इन करें',
      'ja': 'Googleでサインイン',
      'nl': 'Log in met Google',
      'sv': 'Logga in med Google',
      'tr': 'Google ile giriş yap',
      'zh_Hans': '使用 Google 登录',
      'zh_Hant': '使用 Google 登錄',
    },
    'efulmh4b': {
      'en': 'Sign in with Apple',
      'af': 'Meld aan met Apple',
      'ar': 'قم بتسجيل الدخول باستخدام Apple',
      'de': 'Melden Sie sich bei Apple an',
      'es': 'Iniciar sesión con Apple',
      'fr': 'Connectez-vous avec Apple',
      'hi': 'Apple के साथ साइन इन करें',
      'ja': 'Apple でサインインする',
      'nl': 'Log in met Apple',
      'sv': 'Logga in med Apple',
      'tr': 'Apple ile giriş yap',
      'zh_Hans': '使用 Apple 登录',
      'zh_Hant': '使用 Apple 登錄',
    },
    'm5uswki5': {
      'en': 'New to Balance? ',
      'af': 'Nuut by Balans?',
      'ar': 'هل أنت جديد في التوازن؟',
      'de': 'Neu bei Balance?',
      'es': '¿Nuevo en Equilibrio?',
      'fr': 'Nouveau sur l\'équilibre ?',
      'hi': 'संतुलन के लिए नए?',
      'ja': 'バランスを初めて使用しますか?',
      'nl': 'Nieuw bij Balance?',
      'sv': 'Ny på Balance?',
      'tr': 'Balance\'ta yeni misiniz?',
      'zh_Hans': '平衡新手？',
      'zh_Hant': '平衡新手？',
    },
    'tyxaku8b': {
      'en': ' Sign up here',
      'af': 'Teken hier in',
      'ar': 'سجل هنا',
      'de': 'Hier anmelden',
      'es': 'Registrate aquí',
      'fr': 'Inscrivez-vous ici',
      'hi': 'यहां साइन अप करें',
      'ja': 'ここから登録してください',
      'nl': 'Registreer hier',
      'sv': 'Anmäl dig här',
      'tr': 'buradan kaydolun',
      'zh_Hans': '在此注册',
      'zh_Hant': '在此註冊',
    },
    'oo9xr44t': {
      'en': 'Forgot Password?',
      'af': 'Wagwoord vergeet?',
      'ar': 'هل نسيت كلمة السر؟',
      'de': 'Passwort vergessen?',
      'es': '¿Has olvidado tu contraseña?',
      'fr': 'Mot de passe oublié?',
      'hi': 'पासवर्ड भूल गए?',
      'ja': 'パスワードをお忘れですか？',
      'nl': 'Wachtwoord vergeten?',
      'sv': 'Glömt ditt lösenord?',
      'tr': 'Parolanızı mı unuttunuz?',
      'zh_Hans': '忘记密码？',
      'zh_Hant': '忘記密碼？',
    },
    'hpimdzui': {
      'en': 'Home',
      'af': 'Tuis',
      'ar': 'بيت',
      'de': 'Heim',
      'es': 'Hogar',
      'fr': 'Maison',
      'hi': 'घर',
      'ja': '家',
      'nl': 'Thuis',
      'sv': 'Hem',
      'tr': 'Ev',
      'zh_Hans': '家',
      'zh_Hant': '家',
    },
  },
  // Theme
  {
    'ibuj4bsj': {
      'en': 'Theme',
      'af': 'Profiel',
      'ar': 'حساب تعريفي',
      'de': 'Profil',
      'es': 'Perfil',
      'fr': 'Profil',
      'hi': 'प्रोफ़ाइल',
      'ja': 'プロフィール',
      'nl': 'Profiel',
      'sv': 'Profil',
      'tr': 'Profil',
      'zh_Hans': '轮廓',
      'zh_Hant': '輪廓',
    },
    'j3qrz6ly': {
      'en': 'Light',
      'af': 'Lig',
      'ar': 'ضوء',
      'de': 'Licht',
      'es': 'Luz',
      'fr': 'Lumière',
      'hi': 'रोशनी',
      'ja': 'ライト',
      'nl': 'Licht',
      'sv': 'Ljus',
      'tr': 'Işık',
      'zh_Hans': '光',
      'zh_Hant': '光',
    },
    'vanr44g0': {
      'en': 'Dark',
      'af': 'Donker',
      'ar': 'مظلم',
      'de': 'Dunkel',
      'es': 'Oscuro',
      'fr': 'Sombre',
      'hi': 'अँधेरा',
      'ja': '暗い',
      'nl': 'Donker',
      'sv': 'Mörk',
      'tr': 'Karanlık',
      'zh_Hans': '黑暗的',
      'zh_Hant': '黑暗的',
    },
    '8wmoz7jn': {
      'en': 'Custom Background',
      'af': 'Pasgemaakte agtergrond',
      'ar': 'خلفية مخصصة',
      'de': 'Benutzerdefinierter Hintergrund',
      'es': 'Fondo personalizado',
      'fr': 'Arrière-plan personnalisé',
      'hi': 'कस्टम पृष्ठभूमि',
      'ja': 'カスタム背景',
      'nl': 'Eigen achtergrond',
      'sv': 'Egen bakgrund',
      'tr': 'Özel Arkaplan',
      'zh_Hans': '自定义背景',
      'zh_Hant': '自定義背景',
    },
    'jg3z5ja1': {
      'en': 'Theme',
      'af': 'Tema',
      'ar': 'سمة',
      'de': 'Thema',
      'es': 'Tema',
      'fr': 'Thème',
      'hi': 'विषय',
      'ja': 'テーマ',
      'nl': 'Thema',
      'sv': 'Tema',
      'tr': 'Tema',
      'zh_Hans': '主题',
      'zh_Hant': '主題',
    },
  },
  // History
  {
    '8n62lyx9': {
      'en': 'BALANCE.',
      'af': 'BALANS.',
      'ar': 'توازن.',
      'de': 'GLEICHGEWICHT.',
      'es': 'BALANCE.',
      'fr': 'ÉQUILIBRE.',
      'hi': 'संतुलन।',
      'ja': 'バランス。',
      'nl': 'EVENWICHT.',
      'sv': 'BALANS.',
      'tr': 'DENGE.',
      'zh_Hans': '平衡。',
      'zh_Hant': '平衡。',
    },
    't4zmdaj5': {
      'en': 'Workout History',
      'af': 'Gewig',
      'ar': 'وزن',
      'de': 'Gewicht',
      'es': 'Peso',
      'fr': 'Poids',
      'hi': 'वज़न',
      'ja': '重さ',
      'nl': 'Gewicht',
      'sv': 'Vikt',
      'tr': 'Ağırlık',
      'zh_Hans': '重量',
      'zh_Hant': '重量',
    },
    'xy24q8cw': {
      'en': 'Home',
      'af': 'Tuis',
      'ar': 'بيت',
      'de': 'Heim',
      'es': 'Hogar',
      'fr': 'Maison',
      'hi': 'घर',
      'ja': '家',
      'nl': 'Thuis',
      'sv': 'Hem',
      'tr': 'Ev',
      'zh_Hans': '家',
      'zh_Hant': '家',
    },
  },
  // Exercises
  {
    'qryd0q68': {
      'en': 'Exercises',
      'af': 'Profiel',
      'ar': 'حساب تعريفي',
      'de': 'Profil',
      'es': 'Perfil',
      'fr': 'Profil',
      'hi': 'प्रोफ़ाइल',
      'ja': 'プロフィール',
      'nl': 'Profiel',
      'sv': 'Profil',
      'tr': 'Profil',
      'zh_Hans': '轮廓',
      'zh_Hant': '輪廓',
    },
  },
  // historyEmpty
  {
    '6chslxu9': {
      'en': 'No Workouts Performed Yet :(',
      'af': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'nl': '',
      'sv': '',
      'tr': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'co5anqtx': {
      'en': 'Completed Workouts Will Appear Here.',
      'af': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'nl': '',
      'sv': '',
      'tr': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'lss3ce9o': {
      'en': 'START WORKOUT',
      'af': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'nl': '',
      'sv': '',
      'tr': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
  },
  // startWorkoutComp
  {
    'tkhem64b': {
      'en': 'Enter Workout Name...',
      'af': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'nl': '',
      'sv': '',
      'tr': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '3fk3irae': {
      'en': 'FINISH',
      'af': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'nl': '',
      'sv': '',
      'tr': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'f54ueld5': {
      'en': 'New Set',
      'af': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'nl': '',
      'sv': '',
      'tr': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'f07l9xx0': {
      'en': 'Add Exercises',
      'af': 'Oefensessie geskiedenis',
      'ar': 'تاريخ التمرين',
      'de': 'Trainingsverlauf',
      'es': 'Historial de entrenamiento',
      'fr': 'Historique d\'entraînement',
      'hi': 'कसरत का इतिहास',
      'ja': 'トレーニング履歴',
      'nl': 'Trainingsgeschiedenis',
      'sv': 'Träningshistorik',
      'tr': 'Antrenman Geçmişi',
      'zh_Hans': '锻炼历史',
      'zh_Hant': '鍛煉歷史',
    },
    'ioks7rgy': {
      'en': 'CANCEL WORKOUT',
      'af': 'Oefensessie geskiedenis',
      'ar': 'تاريخ التمرين',
      'de': 'Trainingsverlauf',
      'es': 'Historial de entrenamiento',
      'fr': 'Historique d\'entraînement',
      'hi': 'कसरत का इतिहास',
      'ja': 'トレーニング履歴',
      'nl': 'Trainingsgeschiedenis',
      'sv': 'Träningshistorik',
      'tr': 'Antrenman Geçmişi',
      'zh_Hans': '锻炼历史',
      'zh_Hant': '鍛煉歷史',
    },
  },
  // inputWeight
  {
    '6roygyi2': {
      'en': 'Weight',
      'af': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'nl': '',
      'sv': '',
      'tr': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
  },
  // inputReps
  {
    '040b4rai': {
      'en': 'Reps',
      'af': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'nl': '',
      'sv': '',
      'tr': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
  },
  // Miscellaneous
  {
    '4c1yo2p0': {
      'en': '',
      'af': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'nl': '',
      'sv': '',
      'tr': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'se7j07a3': {
      'en': '',
      'af': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'nl': '',
      'sv': '',
      'tr': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'wopa198y': {
      'en':
          'In order to notify you on goals, current workouts and timers, this app requires permission to send notifications.',
      'af':
          'Om jou in kennis te stel oor doelwitte, huidige oefensessies en tydtellers, vereis hierdie toepassing toestemming om kennisgewings te stuur.',
      'ar':
          'لإعلامك بالأهداف والتدريبات الحالية وأجهزة ضبط الوقت ، يتطلب هذا التطبيق إذنًا لإرسال الإشعارات.',
      'de':
          'Um Sie über Ziele, aktuelle Trainingseinheiten und Timer zu informieren, benötigt diese App die Berechtigung zum Senden von Benachrichtigungen.',
      'es':
          'Para notificarle sobre objetivos, entrenamientos actuales y cronómetros, esta aplicación requiere permiso para enviar notificaciones.',
      'fr':
          'Afin de vous informer des objectifs, des entraînements en cours et des minuteurs, cette application nécessite l\'autorisation d\'envoyer des notifications.',
      'hi':
          'आपको लक्ष्य, वर्तमान वर्कआउट और टाइमर के बारे में सूचित करने के लिए, इस ऐप को सूचनाएं भेजने की अनुमति की आवश्यकता होती है।',
      'ja': '目標、現在のワークアウト、タイマーを通知するには、このアプリには通知を送信する権限が必要です。',
      'nl':
          'Om u op de hoogte te houden van doelen, huidige trainingen en timers, heeft deze app toestemming nodig om meldingen te verzenden.',
      'sv':
          'För att meddela dig om mål, aktuella träningspass och timers kräver den här appen tillstånd att skicka aviseringar.',
      'tr':
          'Hedefler, mevcut antrenmanlar ve zamanlayıcılar hakkında sizi bilgilendirmek için bu uygulama, bildirim gönderme izni gerektirir.',
      'zh_Hans': '为了通知您目标、当前锻炼和计时器，此应用程序需要发送通知的权限。',
      'zh_Hant': '為了通知您目標、當前鍛煉和計時器，此應用程序需要發送通知的權限。',
    },
    'zbc6ryng': {
      'en': '',
      'af': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'nl': '',
      'sv': '',
      'tr': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'zq2bczz8': {
      'en': '',
      'af': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'nl': '',
      'sv': '',
      'tr': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'k7q508py': {
      'en': '',
      'af': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'nl': '',
      'sv': '',
      'tr': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'ods4k55o': {
      'en': '',
      'af': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'nl': '',
      'sv': '',
      'tr': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '5asr9mbf': {
      'en': '',
      'af': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'nl': '',
      'sv': '',
      'tr': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'y3yq3gh6': {
      'en': '',
      'af': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'nl': '',
      'sv': '',
      'tr': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'fxd7ca5p': {
      'en': '',
      'af': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'nl': '',
      'sv': '',
      'tr': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'up5x903s': {
      'en': '',
      'af': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'nl': '',
      'sv': '',
      'tr': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'wxi1f4ie': {
      'en': '',
      'af': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'nl': '',
      'sv': '',
      'tr': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'scly4vhu': {
      'en': '',
      'af': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'nl': '',
      'sv': '',
      'tr': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '94m4p4od': {
      'en': '',
      'af': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'nl': '',
      'sv': '',
      'tr': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'rl3gvbrn': {
      'en': '',
      'af': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'nl': '',
      'sv': '',
      'tr': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'xl9hzgs2': {
      'en': '',
      'af': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'nl': '',
      'sv': '',
      'tr': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'v8ovrie9': {
      'en': '',
      'af': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'nl': '',
      'sv': '',
      'tr': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'lxu5ccgl': {
      'en': '',
      'af': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'nl': '',
      'sv': '',
      'tr': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'kso8yuev': {
      'en': '',
      'af': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'nl': '',
      'sv': '',
      'tr': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'fzq3648n': {
      'en': '',
      'af': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'nl': '',
      'sv': '',
      'tr': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '19l3rilb': {
      'en': '',
      'af': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'nl': '',
      'sv': '',
      'tr': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'makplo2w': {
      'en': '',
      'af': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'nl': '',
      'sv': '',
      'tr': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'cpj4ewlj': {
      'en': '',
      'af': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'nl': '',
      'sv': '',
      'tr': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'b32k4hhd': {
      'en': '',
      'af': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'nl': '',
      'sv': '',
      'tr': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'li5ad2vr': {
      'en': '',
      'af': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'nl': '',
      'sv': '',
      'tr': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'suhqc9h5': {
      'en': '',
      'af': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'nl': '',
      'sv': '',
      'tr': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
  },
].reduce((a, b) => a..addAll(b));
