import 'package:flutter/material.dart';
import 'package:flutter/foundation.dart';
import 'package:shared_preferences/shared_preferences.dart';

const _kLocaleStorageKey = '__locale_key__';

class FFLocalizations {
  FFLocalizations(this.locale);

  final Locale locale;

  static FFLocalizations of(BuildContext context) =>
      Localizations.of<FFLocalizations>(context, FFLocalizations)!;

  static List<String> languages() =>
      ['en', 'es', 'zh_Hans', 'zh_Hant', 'de', 'nl', 'ja', 'hi'];

  static late SharedPreferences _prefs;
  static Future initialize() async =>
      _prefs = await SharedPreferences.getInstance();
  static Future storeLocale(String locale) =>
      _prefs.setString(_kLocaleStorageKey, locale);
  static Locale? getStoredLocale() {
    final locale = _prefs.getString(_kLocaleStorageKey);
    return locale != null && locale.isNotEmpty ? createLocale(locale) : null;
  }

  String get languageCode => locale.toString();
  String? get languageShortCode =>
      _languagesWithShortCode.contains(locale.toString())
          ? '${locale.toString()}_short'
          : null;
  int get languageIndex => languages().contains(languageCode)
      ? languages().indexOf(languageCode)
      : 0;

  String getText(String key) =>
      (kTranslationsMap[key] ?? {})[locale.toString()] ?? '';

  String getVariableText({
    String? enText = '',
    String? esText = '',
    String? zh_HansText = '',
    String? zh_HantText = '',
    String? deText = '',
    String? nlText = '',
    String? jaText = '',
    String? hiText = '',
  }) =>
      [
        enText,
        esText,
        zh_HansText,
        zh_HantText,
        deText,
        nlText,
        jaText,
        hiText
      ][languageIndex] ??
      '';

  static const Set<String> _languagesWithShortCode = {
    'ar',
    'az',
    'ca',
    'cs',
    'da',
    'de',
    'dv',
    'en',
    'es',
    'et',
    'fi',
    'fr',
    'gr',
    'he',
    'hi',
    'hu',
    'it',
    'km',
    'ku',
    'mn',
    'ms',
    'no',
    'pt',
    'ro',
    'ru',
    'rw',
    'sv',
    'th',
    'uk',
    'vi',
  };
}

class FFLocalizationsDelegate extends LocalizationsDelegate<FFLocalizations> {
  const FFLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) {
    final language = locale.toString();
    return FFLocalizations.languages().contains(
      language.endsWith('_')
          ? language.substring(0, language.length - 1)
          : language,
    );
  }

  @override
  Future<FFLocalizations> load(Locale locale) =>
      SynchronousFuture<FFLocalizations>(FFLocalizations(locale));

  @override
  bool shouldReload(FFLocalizationsDelegate old) => false;
}

Locale createLocale(String language) => language.contains('_')
    ? Locale.fromSubtags(
        languageCode: language.split('_').first,
        scriptCode: language.split('_').last,
      )
    : Locale(language);

final kTranslationsMap = <Map<String, Map<String, String>>>[
  // Health
  {
    's8r3i5uq': {
      'en': 'BALANCE.',
      'de': 'GLEICHGEWICHT.',
      'es': 'BALANCE.',
      'hi': 'संतुलन।',
      'ja': 'バランス。',
      'nl': 'EVENWICHT.',
      'zh_Hans': '平衡。',
      'zh_Hant': '平衡。',
    },
    'r26xbcvp': {
      'en': 'Health',
      'de': 'Gesundheit',
      'es': 'Salud',
      'hi': 'स्वास्थ्य',
      'ja': '健康',
      'nl': 'Gezondheid',
      'zh_Hans': '健康',
      'zh_Hant': '健康',
    },
  },
  // Settings
  {
    'swzt9q4e': {
      'en': 'Settings',
      'de': 'Einstellungen',
      'es': 'Ajustes',
      'hi': 'समायोजन',
      'ja': '設定',
      'nl': 'Instellingen',
      'zh_Hans': '设置',
      'zh_Hant': '設置',
    },
    'u7hxk5d1': {
      'en': 'Profile',
      'de': 'Profil',
      'es': 'Perfil',
      'hi': 'प्रोफ़ाइल',
      'ja': 'プロフィール',
      'nl': 'Profiel',
      'zh_Hans': '轮廓',
      'zh_Hant': '輪廓',
    },
    'l3mj0bnr': {
      'en': 'Language (English)',
      'de': 'Sprache Englisch)',
      'es': 'Idioma: inglés)',
      'hi': 'भाषा अंग्रेजी)',
      'ja': '言語（英語）',
      'nl': 'Taal Engels)',
      'zh_Hans': '英语语言）',
      'zh_Hant': '英語語言）',
    },
    'a23i2ejl': {
      'en': 'Sound',
      'de': 'Klang',
      'es': 'Sonido',
      'hi': 'आवाज़',
      'ja': '音',
      'nl': 'Geluid',
      'zh_Hans': '声音',
      'zh_Hant': '聲音',
    },
    '5o0l7654': {
      'en': 'Theme',
      'de': 'Thema',
      'es': 'Tema',
      'hi': 'विषय',
      'ja': 'テーマ',
      'nl': 'Thema',
      'zh_Hans': '主题',
      'zh_Hant': '主題',
    },
    'whjue41r': {
      'en': 'Notification Settings',
      'de': 'Benachrichtigungseinstellungen',
      'es': 'Configuración de las notificaciones',
      'hi': 'अधिसूचना सेटिंग्स',
      'ja': '通知設定',
      'nl': 'Notificatie instellingen',
      'zh_Hans': '通知设置',
      'zh_Hant': '通知設置',
    },
    'gdjpjpgx': {
      'en': 'Support',
      'de': 'Unterstützung',
      'es': 'Apoyo',
      'hi': 'सहायता',
      'ja': 'サポート',
      'nl': 'Steun',
      'zh_Hans': '支持',
      'zh_Hant': '支持',
    },
    '5ixzwgjl': {
      'en': 'Settings',
      'de': 'Einstellungen',
      'es': 'Ajustes',
      'hi': 'समायोजन',
      'ja': '設定',
      'nl': 'Instellingen',
      'zh_Hans': '设置',
      'zh_Hant': '設置',
    },
    't9jxktoz': {
      'en': 'Settings',
      'de': 'Einstellungen',
      'es': 'Ajustes',
      'hi': 'समायोजन',
      'ja': '設定',
      'nl': 'Instellingen',
      'zh_Hans': '设置',
      'zh_Hant': '設置',
    },
  },
  // SignUp
  {
    'wwtrpl53': {
      'en': 'BALANCE.',
      'de': 'GLEICHGEWICHT.',
      'es': 'BALANCE.',
      'hi': 'संतुलन।',
      'ja': 'バランス。',
      'nl': 'EVENWICHT.',
      'zh_Hans': '平衡。',
      'zh_Hant': '平衡。',
    },
    'qbq8srbu': {
      'en': 'Create an account',
      'de': 'Ein Konto erstellen',
      'es': 'Crea una cuenta',
      'hi': 'खाता बनाएं',
      'ja': 'アカウントを作成する',
      'nl': 'Account aanmaken',
      'zh_Hans': '创建一个帐户',
      'zh_Hant': '創建一個帳戶',
    },
    '1oc7093e': {
      'en': 'Let\'s get started by filling out the information below.',
      'de': 'Beginnen wir mit dem Ausfüllen der folgenden Informationen.',
      'es': 'Comencemos completando la información a continuación.',
      'hi': 'आइए नीचे दी गई जानकारी भरकर शुरुआत करें।',
      'ja': '以下の情報を入力して始めましょう。',
      'nl':
          'Laten we aan de slag gaan door de onderstaande informatie in te vullen.',
      'zh_Hans': '让我们开始填写以下信息。',
      'zh_Hant': '讓我們開始填寫以下信息。',
    },
    'cvk591dg': {
      'en': 'Email',
      'de': 'Email',
      'es': 'Correo electrónico',
      'hi': 'ईमेल',
      'ja': 'Eメール',
      'nl': 'E-mail',
      'zh_Hans': '电子邮件',
      'zh_Hant': '電子郵件',
    },
    'ygve12uv': {
      'en': 'Password',
      'de': 'Passwort',
      'es': 'Contraseña',
      'hi': 'पासवर्ड',
      'ja': 'パスワード',
      'nl': 'Wachtwoord',
      'zh_Hans': '密码',
      'zh_Hant': '密碼',
    },
    '202aehow': {
      'en': 'Confirm Password',
      'de': 'Bestätige das Passwort',
      'es': 'confirmar Contraseña',
      'hi': 'पासवर्ड की पुष्टि कीजिये',
      'ja': 'パスワードを認証する',
      'nl': 'bevestig wachtwoord',
      'zh_Hans': '确认密码',
      'zh_Hant': '確認密碼',
    },
    'timq8fo3': {
      'en': 'Create Account',
      'de': 'Benutzerkonto erstellen',
      'es': 'Crear una cuenta',
      'hi': 'खाता बनाएं',
      'ja': 'アカウントを作成する',
      'nl': 'Account aanmaken',
      'zh_Hans': '创建账户',
      'zh_Hant': '創建賬戶',
    },
    'x6z5g8v3': {
      'en': 'OR',
      'de': 'ODER',
      'es': 'O',
      'hi': 'या',
      'ja': 'または',
      'nl': 'OF',
      'zh_Hans': '或者',
      'zh_Hant': '或者',
    },
    'v1t3d2ef': {
      'en': 'Continue with Google',
      'de': 'Weiter mit Google',
      'es': 'Continuar con Google',
      'hi': 'Google के साथ जारी रखें',
      'ja': 'Google を続ける',
      'nl': 'Ga verder met Google',
      'zh_Hans': '继续使用谷歌',
      'zh_Hant': '繼續使用谷歌',
    },
    'bb8ouwuh': {
      'en': 'Continue with Apple',
      'de': 'Weiter mit Apple',
      'es': 'Continuar con Apple',
      'hi': 'एप्पल के साथ जारी रखें',
      'ja': 'アップルを使い続ける',
      'nl': 'Ga verder met Apple',
      'zh_Hans': '继续使用苹果',
      'zh_Hant': '繼續使用蘋果',
    },
    'erwy85cy': {
      'en': 'Already have an account? ',
      'de': 'Sie haben bereits ein Konto?',
      'es': '¿Ya tienes una cuenta?',
      'hi': 'क्या आपके पास पहले से एक खाता मौजूद है?',
      'ja': 'すでにアカウントをお持ちですか？',
      'nl': 'Heb je al een account?',
      'zh_Hans': '已经有帐户？',
      'zh_Hant': '已經有帳戶？',
    },
    'i412xonl': {
      'en': ' Sign In here',
      'de': 'Hier anmelden',
      'es': 'Firme aquí',
      'hi': 'यहां साइन इन करो',
      'ja': 'ここにサインインしてください',
      'nl': 'Meld je hier aan',
      'zh_Hans': '在此登录',
      'zh_Hant': '在此登錄',
    },
    'ga9nissl': {
      'en': 'Home',
      'de': 'Heim',
      'es': 'Hogar',
      'hi': 'घर',
      'ja': '家',
      'nl': 'Thuis',
      'zh_Hans': '家',
      'zh_Hant': '家',
    },
  },
  // Workout
  {
    'ghjgh5w0': {
      'en': 'Recommended Workouts',
      'de': 'Empfohlene Trainingseinheiten',
      'es': 'Entrenamientos recomendados',
      'hi': 'अनुशंसित वर्कआउट',
      'ja': '推奨されるトレーニング',
      'nl': 'Aanbevolen trainingen',
      'zh_Hans': '推荐锻炼',
      'zh_Hant': '推薦鍛煉',
    },
    '3qjperj8': {
      'en': 'Cardio',
      'de': 'Cardio',
      'es': 'Cardio',
      'hi': 'कार्डियो',
      'ja': '有酸素運動',
      'nl': 'Cardio',
      'zh_Hans': '有氧运动',
      'zh_Hant': '有氧運動',
    },
    'vf8954ho': {
      'en': 'Strength',
      'de': 'Stärke',
      'es': 'Fortaleza',
      'hi': 'ताकत',
      'ja': '強さ',
      'nl': 'Kracht',
      'zh_Hans': '力量',
      'zh_Hant': '力量',
    },
    'ejlhi3u1': {
      'en': 'Start New Workout',
      'de': 'Starten Sie ein neues Training',
      'es': 'Iniciar nuevo entrenamiento',
      'hi': 'नया वर्कआउट शुरू करें',
      'ja': '新しいワークアウトを開始する',
      'nl': 'Nieuwe training starten',
      'zh_Hans': '开始新的锻炼',
      'zh_Hant': '開始新的鍛煉',
    },
    'imsaf5u9': {
      'en': 'My Routines',
      'de': 'Meine Routinen',
      'es': 'mis rutinas',
      'hi': 'मेरी दिनचर्या',
      'ja': '私のルーティン',
      'nl': 'Mijn routines',
      'zh_Hans': '我的日常',
      'zh_Hant': '我的日常',
    },
    'edubhyg3': {
      'en': 'Push',
      'de': 'Drücken',
      'es': 'Empujar',
      'hi': 'धकेलना',
      'ja': '押す',
      'nl': 'Duw',
      'zh_Hans': '推',
      'zh_Hant': '推',
    },
    'pofpqoyy': {
      'en': 'Last Performed 2 days ago',
      'de': 'Zuletzt vor 2 Tagen aufgeführt',
      'es': 'Realizado por última vez hace 2 días',
      'hi': 'अंतिम प्रदर्शन 2 दिन पहले किया गया',
      'ja': '最後に実行されたのは 2 日前',
      'nl': 'Laatst uitgevoerd 2 dagen geleden',
      'zh_Hans': '上次表演 2 天前',
      'zh_Hant': '上次表演 2 天前',
    },
    'x27b4jfr': {
      'en':
          '5x Benchpress (Barbell)\n4x Incline Benchpress (Barbell)\n3x Overhead Press (Dumbbell)\n3x Chest Fly (Cable)\n3x Tricep Pushdown\n3x Tricep Extension',
      'de':
          '5x Bankdrücken (Langhantel)\n4x Schrägbankdrücken (Langhantel)\n3x Überkopfdrücken (Hantel)\n3x Brustfliege (Kabel)\n3x Trizeps-Pushdown\n3x Trizepsverlängerung',
      'es':
          '5x Press de banca (barra)\n4x Press de banca inclinado (barra)\n3x Press por encima de la cabeza (con mancuernas)\n3 moscas de pecho (cable)\nEmpuje de tríceps 3x\nExtensión de tríceps 3x',
      'hi':
          '5x बेंचप्रेस (बारबेल)\n4x इनक्लाइन बेंचप्रेस (बारबेल)\n3x ओवरहेड प्रेस (डम्बल)\n3x चेस्ट फ्लाई (केबल)\n3x ट्राइसेप पुशडाउन\n3x ट्राइसेप एक्सटेंशन',
      'ja':
          '5x ベンチプレス (バーベル)\n4x インクラインベンチプレス (バーベル)\n3x オーバーヘッド プレス (ダンベル)\n3x チェストフライ (ケーブル)\n3x トライセッププッシュダウン\n3x トライセップエクステンション',
      'nl':
          '5x bankdrukken (halterstang)\n4x Incline Benchpress (Barbell)\n3x overheadpers (halter)\n3x borstvlieg (kabel)\n3x triceps pushdown\n3x Tricep-extensie',
      'zh_Hans':
          '5x 卧推（杠铃）\n4x 上斜卧推（杠铃）\n3x 过头推举（哑铃）\n3x 胸部飞翔（绳索）\n3x 三头肌下压\n3x 三头肌伸展',
      'zh_Hant':
          '5x 臥推（槓鈴）\n4x 上斜臥推（槓鈴）\n3x 過頭推舉（啞鈴）\n3x 胸部飛翔（繩索）\n3x 三頭肌下壓\n3x 三頭肌伸展',
    },
    'z1wdqigq': {
      'en': 'Pull',
      'de': 'Ziehen',
      'es': 'Jalar',
      'hi': 'खींचो',
      'ja': '引く',
      'nl': 'Trekken',
      'zh_Hans': '拉',
      'zh_Hant': '拉',
    },
    'i9k5ep8o': {
      'en': 'Last Performed 4 days ago',
      'de': 'Zuletzt vor 4 Tagen aufgeführt',
      'es': 'Realizado por última vez hace 4 días',
      'hi': 'अंतिम प्रदर्शन 4 दिन पहले किया गया',
      'ja': '最後に実行されたのは 4 日前',
      'nl': '4 dagen geleden voor het laatst uitgevoerd',
      'zh_Hans': '上次表演 4 天前',
      'zh_Hant': '上次表演 4 天前',
    },
    'cyj9xgzi': {
      'en':
          '6x Lat Pulldowns (Cable)\n4x Seated Rows (Cable)\n3x Bicep Curls (Barbell)\n3x T-Bar Rows \n3x Hammer Curls (Dumbbell)\n3x Shrugs (Dumbbell)',
      'de':
          '6x Latzug (Kabelzug)\n4x Sitzrudern (Kabel)\n3x Bizepscurls (Langhantel)\n3x T-Bar-Reihen\n3x Hammercurls (Hantel)\n3x Achselzucken (Hantel)',
      'es':
          '6x Lat Pulldowns (cable)\n4x filas sentadas (cable)\n3x curl de bíceps (barra)\n3 filas con barra en T\n3x Hammer Curls (con mancuernas)\n3x encogimientos de hombros (mancuerna)',
      'hi':
          '6x लैट पुलडाउन (केबल)\n4x बैठी हुई पंक्तियाँ (केबल)\n3x बाइसेप कर्ल्स (बारबेल)\n3x टी-बार पंक्तियाँ\n3x हैमर कर्ल (डम्बल)\n3x श्रग्स (डम्बल)',
      'ja':
          '6x ラットプルダウン (ケーブル)\n4x 着席列 (ケーブル)\n3x 上腕二頭筋カール (バーベル)\n3x Tバー列\n3x ハンマーカール (ダンベル)\n3x シュラッグ (ダンベル)',
      'nl':
          '6x Lat Pulldowns (kabel)\n4x zittende rijen (kabel)\n3x Bicep Curls (Barbell)\n3x T-bar rijen\n3x Hammer Curls (halter)\n3x haalt zijn schouders op (halter)',
      'zh_Hans':
          '6 次高位下拉（绳索）\n4x 坐式划船（缆绳）\n3x 二头肌弯举（杠铃）\n3x T 形划船\n3x 锤式弯举（哑铃）\n3x 耸肩（哑铃）',
      'zh_Hant':
          '6 次高位下拉（繩索）\n4x 坐式划船（纜繩）\n3x 二頭肌彎舉（槓鈴）\n3x T 形划船\n3x 錘式彎舉（啞鈴）\n3x 聳肩（啞鈴）',
    },
    'ov1fjobt': {
      'en': 'Legs',
      'de': 'Beine',
      'es': 'Piernas',
      'hi': 'पैर',
      'ja': '脚',
      'nl': 'Benen',
      'zh_Hans': '腿',
      'zh_Hant': '腿',
    },
    '3ejytq91': {
      'en': 'Last Performed 5 days ago',
      'de': 'Zuletzt vor 5 Tagen aufgeführt',
      'es': 'Última realización hace 5 días',
      'hi': 'अंतिम प्रदर्शन 5 दिन पहले किया गया',
      'ja': '最後に実行されたのは 5 日前',
      'nl': '5 dagen geleden voor het laatst uitgevoerd',
      'zh_Hans': '最后执行时间 5 天前',
      'zh_Hant': '最後執行時間 5 天前',
    },
    'f79y2fm5': {
      'en':
          '5x Deadlift (Barbell)\n4x Squats (Barbell)\n3x Seated Leg Curl (Machine)\n3x Leg Extension (Machine)\n3x Calf raises (Machine)',
      'de':
          '5x Kreuzheben (Langhantel)\n4x Kniebeugen (Langhantel)\n3x Beinbeuger im Sitzen (Maschine)\n3x Beinstrecker (Maschine)\n3x Wadenheben (Maschine)',
      'es':
          '5x peso muerto (barra)\n4x sentadillas (barra)\n3x Curl de piernas sentado (Máquina)\nExtensión de pierna 3x (Máquina)\n3x Elevaciones de pantorrillas (Máquina)',
      'hi':
          '5x डेडलिफ्ट (बारबेल)\n4x स्क्वैट्स (बारबेल)\n3x सीटेड लेग कर्ल (मशीन)\n3x लेग एक्सटेंशन (मशीन)\n3 बार बछड़ा पालना (मशीन)',
      'ja':
          '5x デッドリフト (バーベル)\nスクワット 4 回 (バーベル)\n3x シーテッド レッグ カール (マシン)\n3x レッグエクステンション (マシン)\nカーフレイズ3回（マシン）',
      'nl':
          '5x Deadlift (lange halter)\n4x Squats (lange halter)\n3x Zittende Leg Curl (Machine)\n3x beenverlenging (machine)\n3x kuitverhogingen (machine)',
      'zh_Hans': '5 次硬拉（杠铃）\n4x 深蹲（杠铃）\n3x 坐式腿弯举（机器）\n3x 腿部伸展（机器）\n3 次小腿抬高（机器）',
      'zh_Hant': '5 次硬拉（槓鈴）\n4x 深蹲（槓鈴）\n3x 坐式腿彎舉（機器）\n3x 腿部伸展（機器）\n3 次小腿抬高（機器）',
    },
    'bc7cf98z': {
      'en': 'BALANCE.',
      'de': 'GLEICHGEWICHT.',
      'es': 'BALANCE.',
      'hi': 'संतुलन।',
      'ja': 'バランス。',
      'nl': 'EVENWICHT.',
      'zh_Hans': '平衡。',
      'zh_Hant': '平衡。',
    },
    'yxtektu5': {
      'en': 'Workout',
      'de': 'Trainieren',
      'es': 'Ejercicio',
      'hi': 'कसरत करना',
      'ja': 'いい結果',
      'nl': 'Training',
      'zh_Hans': '锻炼',
      'zh_Hant': '鍛煉',
    },
  },
  // Home
  {
    'n80x0pjn': {
      'en': 'BALANCE.',
      'de': 'GLEICHGEWICHT.',
      'es': 'BALANCE.',
      'hi': 'संतुलन।',
      'ja': 'バランス。',
      'nl': 'EVENWICHT.',
      'zh_Hans': '平衡。',
      'zh_Hant': '平衡。',
    },
    '2tzrzp82': {
      'en': 'Workout History',
      'de': 'Trainingsverlauf',
      'es': 'Historial de entrenamiento',
      'hi': 'कसरत का इतिहास',
      'ja': 'トレーニング履歴',
      'nl': 'Trainingsgeschiedenis',
      'zh_Hans': '锻炼历史',
      'zh_Hant': '鍛煉歷史',
    },
    'tviu6xrv': {
      'en': 'Weight',
      'de': 'Gewicht',
      'es': 'Peso',
      'hi': 'वज़न',
      'ja': '重さ',
      'nl': 'Gewicht',
      'zh_Hans': '重量',
      'zh_Hant': '重量',
    },
    '1s85p23h': {
      'en': 'Day',
      'de': 'Tag',
      'es': 'Día',
      'hi': 'दिन',
      'ja': '日',
      'nl': 'Dag',
      'zh_Hans': '天',
      'zh_Hant': '天',
    },
    '60icw63v': {
      'en': 'Weight',
      'de': 'Gewicht',
      'es': 'Peso',
      'hi': 'वज़न',
      'ja': '重さ',
      'nl': 'Gewicht',
      'zh_Hans': '重量',
      'zh_Hant': '重量',
    },
    'pnq225sh': {
      'en': 'Weight',
      'de': 'Gewicht',
      'es': 'Peso',
      'hi': 'वज़न',
      'ja': '重さ',
      'nl': 'Gewicht',
      'zh_Hans': '重量',
      'zh_Hant': '重量',
    },
    '05ip066l': {
      'en': 'Home',
      'de': 'Heim',
      'es': 'Hogar',
      'hi': 'घर',
      'ja': '家',
      'nl': 'Thuis',
      'zh_Hans': '家',
      'zh_Hant': '家',
    },
  },
  // Profile
  {
    'pmarjxhg': {
      'en': 'Change Picture',
      'de': 'Bild ändern',
      'es': 'Cambiar imagen',
      'hi': 'चित्र बदलें',
      'ja': '写真を変える',
      'nl': 'Verander afbeelding',
      'zh_Hans': '更换图片',
      'zh_Hant': '更換圖片',
    },
    'y9rtj8s1': {
      'en': 'Logout',
      'de': 'Ausloggen',
      'es': 'Cerrar sesión',
      'hi': 'लॉग आउट',
      'ja': 'ログアウト',
      'nl': 'Uitloggen',
      'zh_Hans': '登出',
      'zh_Hant': '登出',
    },
    '4ivamu95': {
      'en': 'Profile',
      'de': 'Profil',
      'es': 'Perfil',
      'hi': 'प्रोफ़ाइल',
      'ja': 'プロフィール',
      'nl': 'Profiel',
      'zh_Hans': '轮廓',
      'zh_Hant': '輪廓',
    },
  },
  // SignIn
  {
    'bki6fcpc': {
      'en': 'BALANCE.',
      'de': 'GLEICHGEWICHT.',
      'es': 'BALANCE.',
      'hi': 'संतुलन।',
      'ja': 'バランス。',
      'nl': 'EVENWICHT.',
      'zh_Hans': '平衡。',
      'zh_Hant': '平衡。',
    },
    '11uarqkt': {
      'en': 'Welcome Back',
      'de': 'Willkommen zurück',
      'es': 'Bienvenido de nuevo',
      'hi': 'वापसी पर स्वागत है',
      'ja': 'おかえり',
      'nl': 'Welkom terug',
      'zh_Hans': '欢迎回来',
      'zh_Hant': '歡迎回來',
    },
    'gauwov03': {
      'en': 'Let\'s get back into it by filling the information below.',
      'de':
          'Lassen Sie uns darauf zurückkommen, indem Sie die folgenden Informationen ausfüllen.',
      'es': 'Volvamos a eso completando la información a continuación.',
      'hi': 'आइए नीचे दी गई जानकारी भरकर इसमें वापस आएं।',
      'ja': '以下の情報を入力して本題に戻りましょう。',
      'nl':
          'Laten we er weer op ingaan door de onderstaande informatie in te vullen.',
      'zh_Hans': '让我们通过填写以下信息来回到它。',
      'zh_Hant': '讓我們通過填寫以下信息來回到它。',
    },
    '221upj73': {
      'en': 'Email',
      'de': 'Email',
      'es': 'Correo electrónico',
      'hi': 'ईमेल',
      'ja': 'Eメール',
      'nl': 'E-mail',
      'zh_Hans': '电子邮件',
      'zh_Hant': '電子郵件',
    },
    'h4vuaqgq': {
      'en': 'Password',
      'de': 'Passwort',
      'es': 'Contraseña',
      'hi': 'पासवर्ड',
      'ja': 'パスワード',
      'nl': 'Wachtwoord',
      'zh_Hans': '密码',
      'zh_Hant': '密碼',
    },
    'y0ybyt83': {
      'en': 'Sign In',
      'de': 'Anmelden',
      'es': 'Iniciar sesión',
      'hi': 'दाखिल करना',
      'ja': 'サインイン',
      'nl': 'Aanmelden',
      'zh_Hans': '登入',
      'zh_Hant': '登入',
    },
    'x1cw61qr': {
      'en': 'OR',
      'de': 'ODER',
      'es': 'O',
      'hi': 'या',
      'ja': 'または',
      'nl': 'OF',
      'zh_Hans': '或者',
      'zh_Hant': '或者',
    },
    'jrdt1yo5': {
      'en': 'Sign in with Google',
      'de': 'Anmeldung mit Google',
      'es': 'Inicia sesión con Google',
      'hi': 'Google से साइन इन करें',
      'ja': 'Googleでサインイン',
      'nl': 'Log in met Google',
      'zh_Hans': '使用 Google 登录',
      'zh_Hant': '使用 Google 登錄',
    },
    'efulmh4b': {
      'en': 'Sign in with Apple',
      'de': 'Melden Sie sich bei Apple an',
      'es': 'Iniciar sesión con Apple',
      'hi': 'Apple के साथ साइन इन करें',
      'ja': 'Apple でサインインする',
      'nl': 'Log in met Apple',
      'zh_Hans': '使用 Apple 登录',
      'zh_Hant': '使用 Apple 登錄',
    },
    'm5uswki5': {
      'en': 'New to Balance? ',
      'de': 'Neu bei Balance?',
      'es': '¿Nuevo en Equilibrio?',
      'hi': 'संतुलन के लिए नए?',
      'ja': 'バランスを初めて使用しますか?',
      'nl': 'Nieuw bij Balance?',
      'zh_Hans': '平衡新手？',
      'zh_Hant': '平衡新手？',
    },
    'tyxaku8b': {
      'en': ' Sign up here',
      'de': 'Hier anmelden',
      'es': 'Registrate aquí',
      'hi': 'यहां साइन अप करें',
      'ja': 'ここから登録してください',
      'nl': 'Registreer hier',
      'zh_Hans': '在此注册',
      'zh_Hant': '在此註冊',
    },
    'oo9xr44t': {
      'en': 'Forgot Password?',
      'de': 'Passwort vergessen?',
      'es': '¿Has olvidado tu contraseña?',
      'hi': 'पासवर्ड भूल गए?',
      'ja': 'パスワードをお忘れですか？',
      'nl': 'Wachtwoord vergeten?',
      'zh_Hans': '忘记密码？',
      'zh_Hant': '忘記密碼？',
    },
    'hpimdzui': {
      'en': 'Home',
      'de': 'Heim',
      'es': 'Hogar',
      'hi': 'घर',
      'ja': '家',
      'nl': 'Thuis',
      'zh_Hans': '家',
      'zh_Hant': '家',
    },
  },
  // Miscellaneous
  {
    '4c1yo2p0': {
      'en': '',
      'de': '',
      'es': '',
      'hi': '',
      'ja': '',
      'nl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'se7j07a3': {
      'en': '',
      'de': '',
      'es': '',
      'hi': '',
      'ja': '',
      'nl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'zbc6ryng': {
      'en': '',
      'de': '',
      'es': '',
      'hi': '',
      'ja': '',
      'nl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'zq2bczz8': {
      'en': '',
      'de': '',
      'es': '',
      'hi': '',
      'ja': '',
      'nl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'k7q508py': {
      'en': '',
      'de': '',
      'es': '',
      'hi': '',
      'ja': '',
      'nl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'ods4k55o': {
      'en': '',
      'de': '',
      'es': '',
      'hi': '',
      'ja': '',
      'nl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '5asr9mbf': {
      'en': '',
      'de': '',
      'es': '',
      'hi': '',
      'ja': '',
      'nl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'y3yq3gh6': {
      'en': '',
      'de': '',
      'es': '',
      'hi': '',
      'ja': '',
      'nl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'fxd7ca5p': {
      'en': '',
      'de': '',
      'es': '',
      'hi': '',
      'ja': '',
      'nl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'up5x903s': {
      'en': '',
      'de': '',
      'es': '',
      'hi': '',
      'ja': '',
      'nl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'wxi1f4ie': {
      'en': '',
      'de': '',
      'es': '',
      'hi': '',
      'ja': '',
      'nl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'scly4vhu': {
      'en': '',
      'de': '',
      'es': '',
      'hi': '',
      'ja': '',
      'nl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '94m4p4od': {
      'en': '',
      'de': '',
      'es': '',
      'hi': '',
      'ja': '',
      'nl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'rl3gvbrn': {
      'en': '',
      'de': '',
      'es': '',
      'hi': '',
      'ja': '',
      'nl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'xl9hzgs2': {
      'en': '',
      'de': '',
      'es': '',
      'hi': '',
      'ja': '',
      'nl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'v8ovrie9': {
      'en': '',
      'de': '',
      'es': '',
      'hi': '',
      'ja': '',
      'nl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'lxu5ccgl': {
      'en': '',
      'de': '',
      'es': '',
      'hi': '',
      'ja': '',
      'nl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'kso8yuev': {
      'en': '',
      'de': '',
      'es': '',
      'hi': '',
      'ja': '',
      'nl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'fzq3648n': {
      'en': '',
      'de': '',
      'es': '',
      'hi': '',
      'ja': '',
      'nl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '19l3rilb': {
      'en': '',
      'de': '',
      'es': '',
      'hi': '',
      'ja': '',
      'nl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'makplo2w': {
      'en': '',
      'de': '',
      'es': '',
      'hi': '',
      'ja': '',
      'nl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'cpj4ewlj': {
      'en': '',
      'de': '',
      'es': '',
      'hi': '',
      'ja': '',
      'nl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'b32k4hhd': {
      'en': '',
      'de': '',
      'es': '',
      'hi': '',
      'ja': '',
      'nl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'li5ad2vr': {
      'en': '',
      'de': '',
      'es': '',
      'hi': '',
      'ja': '',
      'nl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'suhqc9h5': {
      'en': '',
      'de': '',
      'es': '',
      'hi': '',
      'ja': '',
      'nl': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
  },
].reduce((a, b) => a..addAll(b));
